
# Site settings
title: Lantian Zhu
name: Lantian Zhu
subtitle:  PhD Candidate
email: zhulantian93@163.com
description: >
   Graduate in Econ
baseurl: ""
url: "https://lantianzhu.github.io/"
github_username:  Lantian Zhu
disqus_baseurl: "https://lantianzhu.github.io//"
disqus_shortname: https-lantian-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Larry Lantian Zhu"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: LantianZhu
    url: https://lantianzhu.github.io/
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: larry LantianZhu
    url: https://www.linkedin.cn/incareer/in/ACoAABrZTJMB9RCzBzqpxqQsAF2BEQwyvOVfovg
    desc: Connect with me on LinkedIn
    share: true
